using QubeFin.Persistence.Models.Hrms;
using Entity = QubeFin.Persistence.Entities.TblInterviewCandidate;

namespace QubeFin.Persistence.Mappers.Hrms;

public static class CandidateMapper
{
    public static Candidate ToDomain(this Entity entity)
    {
        return new Candidate(
            entity.Id,
            entity.CompanyId,
            entity.FirstName,
            entity.MiddleName,
            entity.LastName,
            entity.Gender,
            entity.FatherName,
            entity.MobileNo,
            entity.Email,
            entity.HouseNo,
            entity.RoadName,
            entity.LandMark,
            entity.AdministrativeUnitId,
            entity.PoliceStationId,
            entity.PostOfficeId,
            entity.PinCode,
            entity.ReferenceNo,
            entity.InterviewDate,
            entity.InterviewTime,
            entity.DepartmentId,
            entity.InterviewPost,
            entity.VenueOrganizationUnitId,
            entity.InterviewMode,
            entity.ReferedBy,
            entity.RecruitmentSource,
            entity.VacancyReference,
            entity.CurrentSalary,
            entity.ExpectedSalary,
            entity.NoticePeriodInDays,
            entity.EarliestJoiningDate,
            entity.IsWillingRelocate,
            entity.PreferredLocation,
            entity.PostedOrganizationUnitId,
            entity.DateOfJoining,
            entity.ReportingTime,
            entity.MonthlyCostCompany,
            entity.OverallPerformance,
            entity.SuitableRoleDepartment,
            entity.RecommendedGradeId,
            entity.IsTrainingRequired,
            entity.RecommendationStatus,
            entity.TotalRatingPoint,
            entity.RatingStatus,
            entity.AadharNumber,
            entity.IsAadharValidated,
            entity.VoterNumber,
            entity.IsVoterValited,
            entity.Pan,
            entity.IsPanValidated,
            entity.IsMobileValidated,
            entity.Uan,
            entity.IsUanVerified,
            entity.IsCreditBureauChecked,
            entity.CreditBureauReportLink,
            entity.CreatedBy,
            entity.CreatedOn,
            entity.ModifiedBy,
            entity.ModifiedOn);
    }

    public static Entity ToEntity(this Candidate candidate)
    {
        return new Entity
        {
            Id = candidate.Id,
            CompanyId = candidate.CompanyId,
            FirstName = candidate.FirstName,
            MiddleName = candidate.MiddleName,
            LastName = candidate.LastName,
            Gender = candidate.Gender,
            FatherName = candidate.FatherName,
            MobileNo = candidate.MobileNo,
            Email = candidate.Email,
            HouseNo = candidate.HouseNo,
            RoadName = candidate.RoadName,
            LandMark = candidate.LandMark,
            AdministrativeUnitId = candidate.AdministrativeUnitId,
            PoliceStationId = candidate.PoliceStationId,
            PostOfficeId = candidate.PostOfficeId,
            PinCode = candidate.PinCode,
            ReferenceNo = candidate.ReferenceNo,
            InterviewDate = candidate.InterviewDate,
            InterviewTime = candidate.InterviewTime,
            DepartmentId = candidate.DepartmentId,
            InterviewPost = candidate.InterviewPost,
            VenueOrganizationUnitId = candidate.VenueOrganizationUnitId,
            InterviewMode = candidate.InterviewMode,
            ReferedBy = candidate.ReferedBy,
            RecruitmentSource = candidate.RecruitmentSource,
            VacancyReference = candidate.VacancyReference,
            CurrentSalary = candidate.CurrentSalary,
            ExpectedSalary = candidate.ExpectedSalary,
            NoticePeriodInDays = candidate.NoticePeriodInDays,
            EarliestJoiningDate = candidate.EarliestJoiningDate,
            IsWillingRelocate = candidate.IsWillingRelocate,
            PreferredLocation = candidate.PreferredLocation,
            PostedOrganizationUnitId = candidate.PostedOrganizationUnitId,
            DateOfJoining = candidate.DateOfJoining,
            ReportingTime = candidate.ReportingTime,
            MonthlyCostCompany = candidate.MonthlyCostCompany,
            OverallPerformance = candidate.OverallPerformance,
            SuitableRoleDepartment = candidate.SuitableRoleDepartment,
            RecommendedGradeId = candidate.RecommendedGradeId,
            IsTrainingRequired = candidate.IsTrainingRequired,
            RecommendationStatus = candidate.RecommendationStatus,
            TotalRatingPoint = candidate.TotalRatingPoint,
            RatingStatus = candidate.RatingStatus,
            AadharNumber = candidate.AadharNumber,
            IsAadharValidated = candidate.IsAadharValidated,
            VoterNumber = candidate.VoterNumber,
            IsVoterValited = candidate.IsVoterValited,
            Pan = candidate.Pan,
            IsPanValidated = candidate.IsPanValidated,
            IsMobileValidated = candidate.IsMobileValidated,
            Uan = candidate.Uan,
            IsUanVerified = candidate.IsUanVerified,
            IsCreditBureauChecked = candidate.IsCreditBureauChecked,
            CreditBureauReportLink = candidate.CreditBureauReportLink,
            CreatedBy = candidate.CreatedBy,
            CreatedOn = candidate.CreatedOn,
            ModifiedBy = candidate.ModifiedBy,
            ModifiedOn = candidate.ModifiedOn
        };
    }
}
