using QubeFin.Persistence.Models.App;
using QubeFin.Persistence.Models.Hrms;
using System.ComponentModel.Design;
using System.Reflection;
using Entity = QubeFin.Persistence.Entities.TblEmployee;

namespace QubeFin.Persistence.Mappers.Hrms;

public static class EmployeeMapper
{
    public static Employee ToDomain(this Entity entity)
    {
        return new Employee(
            entity.Id,
            entity.Salutation,
            entity.FirstName,
            entity.MiddleName,
            entity.LastName,
            entity.Code,
            entity.FatherName,
            entity.MotherName,
            entity.OrganizationUnitId,
            entity.DepartmentId,
            entity.EmployementType,
            entity.DateOfJoining,
            entity.DateOfConfirmation,
            entity.DateOfBirth,
            entity.Gender,
            entity.Religion,
            entity.Caste,
            entity.Nationality,
            entity.BloodGroup,
            entity.DisablityType,
            entity.MaritalStatus,
            entity.MobileNo,
            entity.PersonalEmail,
            entity.EmergencyContactRelation1,
            entity.EmergencyContactName1,
            entity.EmergencyContactMobile1,
            entity.EmergencyContactRelation2,
            entity.EmergencyContactName2,
            entity.EmergencyContactMobile2,
            entity.PermanentHouseNo,
            entity.PermanentRoadName,
            entity.PermanentLandMark,
            entity.PermanentAdministrativeUnitId,
            entity.PermanentPoliceStationId,
            entity.PermanentPostOfficeId,
            entity.PermanentPinCode,
            entity.PermanentOwnerShipOfHouse,
            entity.PermanentDurationOfStayInMonths,
            entity.PresentHouseNo,
            entity.PresentRoadName,
            entity.PresentLandMark,
            entity.PresentAdministrativeUnitId,
            entity.PresentPoliceStationId,
            entity.PresentPostOfficeId,
            entity.PresentPinCode,
            entity.PresentOwnerShipOfHouse,
            entity.PresentDurationOfStayInMonths,
            entity.BankId,
            entity.BankAccountNo,
            entity.BankHolderName,
            entity.BankBranch,
            entity.BankAccountType,
            entity.OfficialEmail,
            entity.IsActive,
            entity.IsPayrollActive,
            entity.CompanyId,
            entity.SeparationDate,
            entity.ReferedBy,
            entity.HowYouKnow,
            entity.LastModifiedBy,
            entity.LastModifiedOn
        );
    }

    public static Entity ToEntity(this Employee domain)
    {
        return new Entity
        {
            Id = domain.Id,
            Salutation = domain.Salutation,
            FirstName = domain.FirstName,
            MiddleName = domain.MiddleName,
            LastName = domain.LastName,
            Code = domain.Code,
            FatherName = domain.FatherName,
            MotherName = domain.MotherName,
            OrganizationUnitId = domain.OrganizationUnitId,
            DepartmentId = domain.DepartmentId,
            EmployementType = domain.EmployementType,
            DateOfJoining = domain.DateOfJoining,
            DateOfConfirmation = domain.DateOfConfirmation,
            DateOfBirth = domain.DateOfBirth,
            Gender = domain.Gender,
            Religion = domain.Religion,
            Caste = domain.Caste,
            Nationality = domain.Nationality,
            BloodGroup = domain.BloodGroup,
            DisablityType = domain.DisablityType,
            MaritalStatus = domain.MaritalStatus,
            MobileNo = domain.MobileNo,
            PersonalEmail = domain.PersonalEmail,
            EmergencyContactRelation1 = domain.EmergencyContactRelation1,
            EmergencyContactName1 = domain.EmergencyContactName1,
            EmergencyContactMobile1 = domain.EmergencyContactMobile1,
            EmergencyContactRelation2 = domain.EmergencyContactRelation2,
            EmergencyContactName2 = domain.EmergencyContactName2,
            EmergencyContactMobile2 = domain.EmergencyContactMobile2,
            PermanentHouseNo = domain.PermanentHouseNo,
            PermanentRoadName = domain.PermanentRoadName,
            PermanentLandMark = domain.PermanentLandMark,
            PermanentAdministrativeUnitId = domain.PermanentAdministrativeUnitId,
            PermanentPoliceStationId = domain.PermanentPoliceStationId,
            PermanentPostOfficeId = domain.PermanentPostOfficeId,
            PermanentPinCode = domain.PermanentPinCode,
            PermanentOwnerShipOfHouse = domain.PermanentOwnerShipOfHouse,
            PermanentDurationOfStayInMonths = domain.PermanentDurationOfStayInMonths,
            PresentHouseNo = domain.PresentHouseNo,
            PresentRoadName = domain.PresentRoadName,
            PresentLandMark = domain.PresentLandMark,
            PresentAdministrativeUnitId = domain.PresentAdministrativeUnitId,
            PresentPoliceStationId = domain.PresentPoliceStationId,
            PresentPostOfficeId = domain.PresentPostOfficeId,
            PresentPinCode = domain.PresentPinCode,
            PresentOwnerShipOfHouse = domain.PresentOwnerShipOfHouse,
            PresentDurationOfStayInMonths = domain.PresentDurationOfStayInMonths,
            BankId = domain.BankId,
            BankAccountNo = domain.BankAccountNo,
            BankHolderName = domain.BankHolderName,
            BankBranch = domain.BankBranch,
            BankAccountType = domain.BankAccountType,
            OfficialEmail = domain.OfficialEmail,
            IsActive = domain.IsActive,
            IsPayrollActive = domain.IsPayrollActive,
            CompanyId = domain.CompanyId,
            SeparationDate = domain.SeparationDate,
            ReferedBy = domain.ReferedBy,
            HowYouKnow = domain.HowYouKnow,
            LastModifiedBy = domain.LastModifiedBy,
            LastModifiedOn = domain.LastModifiedOn
        };
    }
}
